# Generated by Django 3.2.16 on 2023-01-16 09:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_not_yourself_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_yourself_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='not_follow_yourself'),
        ),
    ]
